# Generated by Django 6.0.3 on 2026-04-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '*'), (2, '*'), (3, '*'), (4, '*'), (5, '*')], default=1),
            preserve_default=False,
        ),
    ]
