# Generated by Django 6.0.3 on 2026-05-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_create_at_product_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
