# Generated by Django 6.0.3 on 2026-04-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_namber',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
