# Generated by Django 6.0.3 on 2026-04-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userconfirm_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfirm',
            old_name='name',
            new_name='user',
        ),
    ]
