# Generated by Django 6.0.3 on 2026-04-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_phone_namber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_namber',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
