# Generated by Django 6.0.3 on 2026-05-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customuser_phone_namber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
