# Generated by Django 6.0.3 on 2026-05-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customuser_first_name_customuser_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserConfirm',
        ),
    ]
